### ISSUE TITLE
Material to provide to STAR Panel and CIE - by July 23

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [iantaylor-NOAA/Lingcod_2021#166]
Concluding task for STAT to do and provide for panel and CIE reports (as well as for assessment report)

- [x] Decision tables (star issue #154) with all catch streams [IGT]
For southern model if planned catch streams don't show increasing to target in 10 years may need to switch out one.
Panel keen on a Pstar = 0.4 catch stream
- [x] likelihood profiles (old issue #72) [KFJ] with `model_settings$prior_like <- 1` (see https://github.com/nwfsc-assess/nwfscDiag/issues/6)
- [x] retros with corrected blocks [KFJ]
- [x] figures (unsure if they need all)
  - [x] profile plots
  - [x] retrospectives
  - [ ] other figures (can't remember what)
- [x] r4ss and model files for final (perhaps already done in #161)

**Comment by kellijohnson-NOAA** [comment]
Rerunning retros with better block structure right now.

**Comment by kellijohnson-NOAA** [comment]
Made a [folder on the google drive](https://drive.google.com/drive/folders/19CAreDeyn3qOQWpX7U2Ggx_oNxVa7n6m?usp=sharing) that we can share or zip.

**Comment by iantaylor-NOAA** [comment]
Decision tables added to Google Drive folders using old version of `table_decsision()` (#167).
