### ISSUE TITLE
Address STAR 2017 problems, uncertainties, and recommendations as appropriate

### ISSUE THREAD

**Issue by iantaylor-NOAA** [iantaylor-NOAA/Lingcod_2021#6]
This issue can be used to keep track of this individual issues

**Comment by iantaylor-NOAA** [comment]
The 2017 STAR report note 4 Unresolved Problems, 3 Major Uncertainties, and provided 3 specific recommendations as noted in the following issues
- [ ] #8 STAR 2017 Unresolved Problem 1: include more age data
- [ ] #9 STAR 2017 Unresolved Problem 2: provide more information on consistency among ageing protocols
- [ ] #10 STAR 2017 Unresolved Problem 3: concern about fixing Linf in Northern model
- [ ] #11 STAR 2017 Unresolved Problem 4: models sensitive to structural assumptions
- [ ] #12 STAR 2017 Major Uncertainty 1: stock structure
- [ ] #13 STAR 2017 Major Uncertainty 2: Key productivity parameters
- [ ] #14 STAR 2017 Major Uncertainty 3: Habitat area, north versus south
- [ ] #15 STAR 2017 recommendation 1: cross-validate age-readings
- [ ] #16 STAR 2017 recommendation 2: include more info from Canada and Mexico
- [ ] #17 STAR 2017 recommendation 3: develop a spatially-explicit model rather than independent N & S models
There were also a general list that we should keep in mind
- [ ] #18 STAR 2017 General recommendations for all assessments

**Comment by brianlangseth-NOAA** [comment]
Updated in a6befc6 though can be fine tuned based on models results

**Comment by iantaylor-NOAA** [comment]
@brianlangseth-NOAA, this is great, thank you. I'll add a few tweaks, which is a lot easier than starting from scratch.

**Comment by kellijohnson-NOAA** [comment]
2017 STAR panel recommendations were added to the document thanks to @iantaylor-NOAA and @brianlangseth-NOAA
